# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from datetime import time
from datetime import timedelta
from uuid import UUID

import structlog

from sdtoolplus.autogenerated_graphql_client import AddressCreateInput
from sdtoolplus.autogenerated_graphql_client import AddressTerminateInput
from sdtoolplus.autogenerated_graphql_client import AddressUpdateInput
from sdtoolplus.autogenerated_graphql_client import EmployeeCreateInput
from sdtoolplus.autogenerated_graphql_client import EmployeeUpdateInput
from sdtoolplus.autogenerated_graphql_client import RAValidityInput
from sdtoolplus.depends import GraphQLClient
from sdtoolplus.models import Person

logger = structlog.stdlib.get_logger()


async def create_person(
    gql_client: GraphQLClient,
    cpr: str,
    givenname: str,
    lastname: str,
    dry_run: bool = False,
) -> UUID:
    logger.info("Create new person", cpr=cpr, givenname=givenname, lastname=lastname)

    employee_input = EmployeeCreateInput(
        cpr_number=cpr,
        given_name=givenname,
        surname=lastname,
    )
    logger.debug("Create person payload", payload=employee_input.dict())
    if not dry_run:
        mo_person = await gql_client.create_person(input=employee_input)
    logger.debug("Person created", cpr=cpr)

    return mo_person.uuid


async def update_person(
    gql_client: GraphQLClient,
    uuid: UUID,
    start: datetime,
    person: Person,
    dry_run: bool = False,
) -> None:
    logger.info("Update person")

    payload = EmployeeUpdateInput(
        uuid=uuid,
        cpr_number=person.cpr,
        given_name=person.given_name,
        surname=person.surname,
        validity=RAValidityInput(from_=start, to=None),
    )
    logger.debug("Update person payload", payload=payload.dict())
    if not dry_run:
        await gql_client.update_person(payload)
    logger.debug("Person updated", cpr=person.cpr)


async def create_address(
    gql_client: GraphQLClient,
    person_uuid: UUID,
    value: str,
    from_: datetime,
    visibility_uuid: UUID,
    address_type_uuid: UUID,
) -> UUID:
    logger.info("Create address", address=value, from_=from_)
    addr = await gql_client.create_address(
        AddressCreateInput(
            person=person_uuid,
            visibility=visibility_uuid,
            user_key=value,
            value=value,
            address_type=address_type_uuid,
            validity=RAValidityInput(from_=from_),
        )
    )
    logger.info("Address created", address_uuid=str(addr.uuid))
    return addr.uuid


async def update_address(
    gql_client: GraphQLClient,
    address_uuid: UUID,
    person_uuid: UUID,
    value: str,
    from_: datetime,
    visibility_uuid: UUID,
    address_type_uuid: UUID,
) -> None:
    logger.info("Update address", value=value, from_=from_, address_uuid=address_uuid)
    await gql_client.update_address(
        AddressUpdateInput(
            uuid=address_uuid,
            person=person_uuid,
            visibility=visibility_uuid,
            user_key=value,
            value=value,
            address_type=address_type_uuid,
            validity=RAValidityInput(from_=from_),
        )
    )
    logger.info("Address updated", address_uuid=str(address_uuid))


async def terminate_address(
    gql_client: GraphQLClient,
    address_uuid: UUID,
    terminate_from: datetime,
) -> None:
    logger.info(
        "Terminate address", address_uuid=address_uuid, terminate_from=terminate_from
    )
    await gql_client.terminate_address(
        AddressTerminateInput(
            uuid=address_uuid,
            to=datetime.combine(terminate_from.date(), time.min) - timedelta(days=1),
        )
    )
    logger.debug("Address terminated", address_uuid=str(address_uuid))
