# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime

import pytest
from pydantic import BaseModel

from sdtoolplus.autogenerated_graphql_client import RAValidityInput
from sdtoolplus.mo.timeline import _get_update_validity


@pytest.mark.parametrize(
    "patch_validity_from, patch_validity_to, mo_validity_from, mo_validity_to, expected_from, expected_to",
    [
        (
            datetime(1900, 1, 1),
            None,
            datetime(2000, 1, 1),
            None,
            datetime(2000, 1, 1),
            None,
        ),
        (
            datetime(2000, 1, 1),
            None,
            datetime(1900, 1, 1),
            None,
            datetime(2000, 1, 1),
            None,
        ),
        (
            datetime(2000, 1, 1),
            datetime(2200, 1, 1),
            datetime(2000, 1, 1),
            datetime(2100, 1, 1),
            datetime(2000, 1, 1),
            datetime(2100, 1, 1),
        ),
        (
            datetime(2000, 1, 1),
            datetime(2100, 1, 1),
            datetime(2000, 1, 1),
            datetime(2200, 1, 1),
            datetime(2000, 1, 1),
            datetime(2100, 1, 1),
        ),
    ],
)
def test__get_update_validity(
    patch_validity_from: datetime,
    patch_validity_to: datetime | None,
    mo_validity_from: datetime,
    mo_validity_to: datetime | None,
    expected_from: datetime,
    expected_to: datetime | None,
):
    # Arrange
    class CodegenValidity(BaseModel):
        from_: datetime
        to: datetime | None

    patch_validity = CodegenValidity(from_=patch_validity_from, to=patch_validity_to)
    mo_validity = RAValidityInput(from_=mo_validity_from, to=mo_validity_to)

    # Act
    actual_validity = _get_update_validity(patch_validity, mo_validity)

    # Assert
    assert actual_validity == RAValidityInput(from_=expected_from, to=expected_to)
