# Generated by ariadne-codegen on 2024-05-10 16:01
# Source: queries.graphql
from uuid import UUID

from .base_model import BaseModel


class TestingCreateEngagement(BaseModel):
    engagement_create: "TestingCreateEngagementEngagementCreate"


class TestingCreateEngagementEngagementCreate(BaseModel):
    uuid: UUID


TestingCreateEngagement.update_forward_refs()
TestingCreateEngagementEngagementCreate.update_forward_refs()
