# Generated by ariadne-codegen on 2024-03-07 13:26
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class TestingGetFacetClass(BaseModel):
    facets: "TestingGetFacetClassFacets"


class TestingGetFacetClassFacets(BaseModel):
    objects: List["TestingGetFacetClassFacetsObjects"]


class TestingGetFacetClassFacetsObjects(BaseModel):
    current: Optional["TestingGetFacetClassFacetsObjectsCurrent"]


class TestingGetFacetClassFacetsObjectsCurrent(BaseModel):
    classes: List["TestingGetFacetClassFacetsObjectsCurrentClasses"]


class TestingGetFacetClassFacetsObjectsCurrentClasses(BaseModel):
    uuid: UUID
    user_key: str
    name: str
    scope: Optional[str]


TestingGetFacetClass.update_forward_refs()
TestingGetFacetClassFacets.update_forward_refs()
TestingGetFacetClassFacetsObjects.update_forward_refs()
TestingGetFacetClassFacetsObjectsCurrent.update_forward_refs()
TestingGetFacetClassFacetsObjectsCurrentClasses.update_forward_refs()
