# Generated by ariadne-codegen on 2024-03-06 11:32
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class TestingGetOrgUnitTypes(BaseModel):
    facets: "TestingGetOrgUnitTypesFacets"


class TestingGetOrgUnitTypesFacets(BaseModel):
    objects: List["TestingGetOrgUnitTypesFacetsObjects"]


class TestingGetOrgUnitTypesFacetsObjects(BaseModel):
    current: Optional["TestingGetOrgUnitTypesFacetsObjectsCurrent"]


class TestingGetOrgUnitTypesFacetsObjectsCurrent(BaseModel):
    classes: List["TestingGetOrgUnitTypesFacetsObjectsCurrentClasses"]


class TestingGetOrgUnitTypesFacetsObjectsCurrentClasses(BaseModel):
    uuid: UUID
    user_key: str
    name: str
    scope: Optional[str]


TestingGetOrgUnitTypes.update_forward_refs()
TestingGetOrgUnitTypesFacets.update_forward_refs()
TestingGetOrgUnitTypesFacetsObjects.update_forward_refs()
TestingGetOrgUnitTypesFacetsObjectsCurrent.update_forward_refs()
TestingGetOrgUnitTypesFacetsObjectsCurrentClasses.update_forward_refs()
