# Generated by ariadne-codegen on 2024-05-10 16:01
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetFacetClass(BaseModel):
    classes: "GetFacetClassClasses"


class GetFacetClassClasses(BaseModel):
    objects: List["GetFacetClassClassesObjects"]


class GetFacetClassClassesObjects(BaseModel):
    current: Optional["GetFacetClassClassesObjectsCurrent"]


class GetFacetClassClassesObjectsCurrent(BaseModel):
    uuid: UUID
    user_key: str
    name: str
    scope: Optional[str]


GetFacetClass.update_forward_refs()
GetFacetClassClasses.update_forward_refs()
GetFacetClassClassesObjects.update_forward_refs()
GetFacetClassClassesObjectsCurrent.update_forward_refs()
