# Generated by ariadne-codegen on 2025-03-27 10:22
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetFacetUuid(BaseModel):
    facets: "GetFacetUuidFacets"


class GetFacetUuidFacets(BaseModel):
    objects: List["GetFacetUuidFacetsObjects"]


class GetFacetUuidFacetsObjects(BaseModel):
    uuid: UUID


GetFacetUuid.update_forward_refs()
GetFacetUuidFacets.update_forward_refs()
GetFacetUuidFacetsObjects.update_forward_refs()
