# Generated by ariadne-codegen on 2025-04-09 12:51
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TerminatePersonAddress(BaseModel):
    address_terminate: "TerminatePersonAddressAddressTerminate"


class TerminatePersonAddressAddressTerminate(BaseModel):
    uuid: UUID


TerminatePersonAddress.update_forward_refs()
TerminatePersonAddressAddressTerminate.update_forward_refs()
