# Generated by ariadne-codegen on 2025-04-09 12:51
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdatePersonAddress(BaseModel):
    address_update: "UpdatePersonAddressAddressUpdate"


class UpdatePersonAddressAddressUpdate(BaseModel):
    uuid: UUID


UpdatePersonAddress.update_forward_refs()
UpdatePersonAddressAddressUpdate.update_forward_refs()
