# Generated by ariadne-codegen on 2025-04-30 14:48
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateLeave(BaseModel):
    leave_update: "UpdateLeaveLeaveUpdate"


class UpdateLeaveLeaveUpdate(BaseModel):
    uuid: UUID


UpdateLeave.update_forward_refs()
UpdateLeaveLeaveUpdate.update_forward_refs()
