# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from datetime import date
from datetime import datetime
from unittest.mock import AsyncMock
from unittest.mock import MagicMock
from unittest.mock import patch
from uuid import UUID
from uuid import uuid4
from zoneinfo import ZoneInfo

import aio_pika
import pytest
from fastapi import Depends
from fastapi import FastAPI
from fastapi.testclient import TestClient
from fastramqpi.pytest_util import retry
from freezegun import freeze_time
from httpx import AsyncClient
from more_itertools import one
from respx import MockRouter

from sdtoolplus.autogenerated_graphql_client import EmployeeCreateInput
from sdtoolplus.autogenerated_graphql_client import EmployeeFilter
from sdtoolplus.autogenerated_graphql_client import EngagementCreateInput
from sdtoolplus.autogenerated_graphql_client import EventSendInput
from sdtoolplus.autogenerated_graphql_client import ManagerCreateInput
from sdtoolplus.autogenerated_graphql_client import OrganisationUnitCreateInput
from sdtoolplus.autogenerated_graphql_client import OrganisationUnitFilter
from sdtoolplus.autogenerated_graphql_client import RAValidityInput
from sdtoolplus.autogenerated_graphql_client import TestingCreateOrgUnitOrgUnitCreate
from sdtoolplus.depends import GraphQLClient
from sdtoolplus.events import process_sd_amqp_employment_event
from sdtoolplus.events import sd_api_open
from sdtoolplus.mo.timelines.common import get_class
from sdtoolplus.mo.timelines.common import mo_end_to_timeline_end
from sdtoolplus.mo.timelines.common import timeline_interval_to_mo_validity
from sdtoolplus.mo.timelines.engagement import get_engagement_filter
from sdtoolplus.mo.timelines.engagement import get_engagement_types
from sdtoolplus.mo_org_unit_importer import OrgUnitLevelUUID
from sdtoolplus.models import POSITIVE_INFINITY
from sdtoolplus.models import EngType
from sdtoolplus.models import PersonAndEmploymentGraphQLEvent
from sdtoolplus.types import CPRNumber
from tests.integration.conftest import UNKNOWN_UNIT

# In production the SD AMQP events arrive on a dedicated SD broker. That broker
# (the `sd-amqp` service) is not available in the CI pipeline, so for the
# integration test we point the SD AMQP integration at the os2mo `msg-broker`
# instead.
SD_AMQP_URL = "amqp://guest:guest@msg-broker:5672/"

# The queues the SD AMQP integration consumes from. In production these are
# declared by SD; the application only consumes them (passively).
SD_AMQP_QUEUES = ("employment-events", "org-events", "person-events")


@pytest.fixture
async def sd_amqp_queues() -> None:
    """Declare the SD AMQP queues on the message broker.

    The application consumes these queues passively (it does not declare them),
    so they must exist before the application connects. This fixture must run
    before the application server is started (i.e. before the `test_client`
    fixture).

    The queues are durable and are not part of the database snapshot, so any
    messages left over from a previous test would otherwise linger. We therefore
    purge them in case they already exist.
    """
    connection = await aio_pika.connect(SD_AMQP_URL)
    try:
        channel = await connection.channel()
        for name in SD_AMQP_QUEUES:
            queue = await channel.declare_queue(name, durable=True)
            await queue.purge()
    finally:
        await connection.close()


@pytest.mark.envvar(
    {
        "MODE": "region",
        "UNKNOWN_UNIT": str(UNKNOWN_UNIT),
        "APPLY_NY_LOGIC": "false",
        "EVENT_BASED_SYNC": "true",
        "MO_SUBTREE_PATHS_FOR_ROOT": '{"II": ["12121212-1212-1212-1212-121212121212", "10000000-0000-0000-0000-000000000000"]}',
        "PREFIX_ENGAGEMENT_USER_KEYS": "true",
    }
)
@pytest.mark.integration_test
async def test_reconcile_person_and_related_objects(
    respx_mock: MockRouter,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    base_tree_builder: TestingCreateOrgUnitOrgUnitCreate,
    job_function_5678: UUID,
    job_function_9000: UUID,
) -> None:
    """Test that changes in MO are reconciled.

    This is a simple smoke-test to ensure that the GraphQL event system is
    properly configured.
    """
    person_cpr = CPRNumber("0101011234")
    employment_identifier = "12345"
    engagement_user_key = f"II-{employment_identifier}"

    # Ensure that the person does not exist yet
    mo_person = await graphql_client.get_person(cpr=person_cpr)
    assert mo_person.objects == []

    # Configure SD API GetPerson mock
    today_sd_format = date.strftime(date.today(), "%Y-%m-%d")
    today_url_format = date.strftime(date.today(), "%d.%m.%Y")
    respx_mock.get(
        f"https://service.sd.dk/sdws/GetPerson20111201?InstitutionIdentifier=II&EffectiveDate={today_url_format}&PersonCivilRegistrationIdentifier={person_cpr}&StatusActiveIndicator=True&StatusPassiveIndicator=True&ContactInformationIndicator=True&PostalAddressIndicator=True"
    ).respond(
        content_type="text/xml;charset=UTF-8",
        content=f"""<?xml version="1.0" encoding="UTF-8" ?>
            <GetPerson20111201 creationDateTime="2025-04-09T09:47:55">
                <RequestStructure>
                    <InstitutionIdentifier>II</InstitutionIdentifier>
                    <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
                    <EffectiveDate>{today_sd_format}</EffectiveDate>
                    <StatusActiveIndicator>true</StatusActiveIndicator>
                    <StatusPassiveIndicator>false</StatusPassiveIndicator>
                    <ContactInformationIndicator>false</ContactInformationIndicator>
                    <PostalAddressIndicator>false</PostalAddressIndicator>
                </RequestStructure>
                <Person>
                    <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
                    <PersonGivenName>Chuck</PersonGivenName>
                    <PersonSurnameName>Norris</PersonSurnameName>
                    <Employment>
                        <EmploymentIdentifier>{employment_identifier}</EmploymentIdentifier>
                    </Employment>
                </Person>
            </GetPerson20111201>
        """,
    )

    # Create person with the wrong name
    person_uuid = (
        await graphql_client.create_person(
            input=EmployeeCreateInput(
                cpr_number=person_cpr,
                given_name="RECONCILE",
                surname="ME",
            )
        )
    ).uuid

    # Ensure that the name is reconciled
    @retry()  # type: ignore[no-redef]
    async def verify() -> None:
        mo_person = await graphql_client.get_person_timeline(
            filter=EmployeeFilter(
                cpr_numbers=[person_cpr],
                from_date=None,
                to_date=None,
            )
        )
        validities = one(mo_person.objects).validities
        names = {(v.given_name, v.surname) for v in validities}
        assert names == {("RECONCILE", "ME"), ("Chuck", "Norris")}

    await verify()

    # Configure SD API GetEmploymentChanged mock
    respx_mock.get(
        "https://service.sd.dk/sdws/GetEmploymentChanged20111201?InstitutionIdentifier=II&PersonCivilRegistrationIdentifier=0101011234&EmploymentIdentifier=12345&ActivationDate=01.01.0001&DeactivationDate=31.12.9999&DepartmentIndicator=True&EmploymentStatusIndicator=True&ProfessionIndicator=True&SalaryAgreementIndicator=False&SalaryCodeGroupIndicator=False&WorkingTimeIndicator=True&UUIDIndicator=True"
    ).respond(
        content_type="text/xml;charset=UTF-8",
        content="""<?xml version="1.0" encoding="UTF-8"?>
        <GetEmploymentChanged20111201 creationDateTime="2025-03-10T13:50:06">
          <RequestStructure>
            <InstitutionIdentifier>II</InstitutionIdentifier>
            <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
            <ActivationDate>2000-01-01</ActivationDate>
            <DeactivationDate>2006-12-31</DeactivationDate>
            <DepartmentIndicator>true</DepartmentIndicator>
            <EmploymentStatusIndicator>true</EmploymentStatusIndicator>
            <ProfessionIndicator>true</ProfessionIndicator>
            <SalaryAgreementIndicator>false</SalaryAgreementIndicator>
            <SalaryCodeGroupIndicator>false</SalaryCodeGroupIndicator>
            <WorkingTimeIndicator>false</WorkingTimeIndicator>
            <UUIDIndicator>true</UUIDIndicator>
          </RequestStructure>
          <Person>
            <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
            <Employment>
              <EmploymentIdentifier>12345</EmploymentIdentifier>
              <EmploymentDate>2000-01-01</EmploymentDate>
              <AnniversaryDate>2000-01-01</AnniversaryDate>
              <EmploymentDepartment>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <DepartmentIdentifier>dep1</DepartmentIdentifier>
                <DepartmentUUIDIdentifier>10000000-0000-0000-0000-000000000000</DepartmentUUIDIdentifier>
              </EmploymentDepartment>
              <Profession>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <JobPositionIdentifier>9000</JobPositionIdentifier>
                <EmploymentName>name4</EmploymentName>
                <AppointmentCode>0</AppointmentCode>
              </Profession>
              <EmploymentStatus>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <EmploymentStatusCode>1</EmploymentStatusCode>
              </EmploymentStatus>
              <WorkingTime>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <OccupationRate>1.0000</OccupationRate>
                <SalaryRate>1.0000</SalaryRate>
                <SalariedIndicator>true</SalariedIndicator>
                <FullTimeIndicator>true</FullTimeIndicator>
              </WorkingTime>
            </Employment>
          </Person>
        </GetEmploymentChanged20111201>
    """,
    )

    # Create engagement with the wrong job function
    engagement_types = await get_engagement_types(graphql_client)
    await graphql_client.create_engagement(
        EngagementCreateInput(
            user_key=engagement_user_key,
            validity=RAValidityInput(from_=datetime(2000, 1, 1), to=None),
            person=person_uuid,
            org_unit=UUID("10000000-0000-0000-0000-000000000000"),
            engagement_type=engagement_types[EngType.MONTHLY_FULL_TIME],
            job_function=job_function_5678,
        )
    )

    # Ensure that the org unit is reconciled
    @retry()  # type: ignore[no-redef]
    async def verify() -> None:
        mo_engagement = await graphql_client.get_engagement_timeline(
            get_engagement_filter(
                person=person_uuid,
                user_key=engagement_user_key,
                from_date=None,
                to_date=None,
            )
        )
        validities = one(mo_engagement.objects).validities
        job_function_uuids = {v.job_function_uuid for v in validities}
        assert job_function_uuids == {job_function_9000}

    await verify()

    # TODO: verify address sync


@pytest.mark.envvar(
    {
        "MODE": "region",
        "UNKNOWN_UNIT": str(UNKNOWN_UNIT),
        "APPLY_NY_LOGIC": "false",
        "EVENT_BASED_SYNC": "true",
        "MO_SUBTREE_PATHS_FOR_ROOT": '{"II": ["12121212-1212-1212-1212-121212121212", "10000000-0000-0000-0000-000000000000"]}',
        "PREFIX_ENGAGEMENT_USER_KEYS": "true",
    }
)
@pytest.mark.integration_test
async def test_reconcile_org_unit_and_related_objects(
    respx_mock: MockRouter,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    base_tree_builder: TestingCreateOrgUnitOrgUnitCreate,
    org_unit_type: UUID,
    org_unit_levels: dict[str, OrgUnitLevelUUID],
) -> None:
    """Test that changes in MO are reconciled.

    This is a simple smoke-test to ensure that the GraphQL event system is
    properly configured.
    """
    org_unit_uuid = uuid4()

    # Configure SD API GetDepartment mock
    respx_mock.get(
        f"https://service.sd.dk/sdws/GetDepartment20111201?InstitutionIdentifier=II&DepartmentUUIDIdentifier={org_unit_uuid}&ActivationDate=01.01.0001&DeactivationDate=31.12.9999&ContactInformationIndicator=True&DepartmentNameIndicator=True&PostalAddressIndicator=True&ProductionUnitIndicator=True&UUIDIndicator=True"
    ).respond(
        content_type="text/xml;charset=UTF-8",
        content=f"""<?xml version="1.0" encoding="UTF-8"?>
            <GetDepartment20111201 creationDateTime="2025-02-18T10:41:08">
                <RequestStructure>
                    <InstitutionIdentifier>II</InstitutionIdentifier>
                    <DepartmentUUIDIdentifier>{org_unit_uuid}</DepartmentUUIDIdentifier>
                    <ActivationDate>1930-02-18</ActivationDate>
                    <DeactivationDate>9999-12-31</DeactivationDate>
                    <ContactInformationIndicator>false</ContactInformationIndicator>
                    <DepartmentNameIndicator>true</DepartmentNameIndicator>
                    <EmploymentDepartmentIndicator>false</EmploymentDepartmentIndicator>
                    <PostalAddressIndicator>false</PostalAddressIndicator>
                    <ProductionUnitIndicator>false</ProductionUnitIndicator>
                    <UUIDIndicator>true</UUIDIndicator>
                </RequestStructure>
                <RegionIdentifier>RI</RegionIdentifier>
                <RegionUUIDIdentifier>838b8691-7785-4f64-a83a-b383567dd171</RegionUUIDIdentifier>
                <InstitutionIdentifier>II</InstitutionIdentifier>
                <InstitutionUUIDIdentifier>d6024493-a920-4040-9876-9faaae88efc1</InstitutionUUIDIdentifier>
                <Department>
                    <ActivationDate>2001-01-01</ActivationDate>
                    <DeactivationDate>9999-12-31</DeactivationDate>
                    <DepartmentIdentifier>ABCD</DepartmentIdentifier>
                    <DepartmentUUIDIdentifier>{org_unit_uuid}</DepartmentUUIDIdentifier>
                    <DepartmentLevelIdentifier>NY0-niveau</DepartmentLevelIdentifier>
                    <DepartmentName>name1</DepartmentName>
                </Department>
            </GetDepartment20111201>
        """,
    )
    # Configure SD API department-parent-history mock
    respx_mock.get(
        f"https://service.sd.dk/api-gateway/organization/public/api/v1/organizations/uuids/{org_unit_uuid}/department-parent-history"
    ).respond(
        json=[
            {
                "startDate": "2001-01-01",
                "endDate": "9999-12-31",
                "parentUuid": "10000000-0000-0000-0000-000000000000",
            },
        ],
    )

    # Create org unit with the wrong name
    org_unit_uuid = (
        await graphql_client.create_org_unit(
            input=OrganisationUnitCreateInput(
                uuid=org_unit_uuid,
                validity=RAValidityInput(from_=datetime(2000, 1, 1), to=None),
                name="RECONCILE ME",
                user_key="II-ABCD",
                parent=UUID("10000000-0000-0000-0000-000000000000"),
                org_unit_type=org_unit_type,
                org_unit_level=org_unit_levels["Afdelings-niveau"],
            )
        )
    ).uuid

    # Ensure that the name is reconciled
    @retry()
    async def verify() -> None:
        mo_org_unit = await graphql_client.get_org_unit_timeline(
            OrganisationUnitFilter(uuids=[org_unit_uuid], from_date=None, to_date=None)
        )
        validities = one(mo_org_unit.objects).validities
        names = {v.name for v in validities}
        assert names == {"name1"}

    await verify()

    # TODO: verify address sync


@pytest.mark.envvar(
    {
        "MODE": "region",
        "UNKNOWN_UNIT": str(UNKNOWN_UNIT),
        "APPLY_NY_LOGIC": "false",
        "EVENT_BASED_SYNC": "true",
        "MO_SUBTREE_PATHS_FOR_ROOT": '{"II": ["12121212-1212-1212-1212-121212121212", "10000000-0000-0000-0000-000000000000"]}',
        "PREFIX_ENGAGEMENT_USER_KEYS": "true",
    }
)
@pytest.mark.integration_test
@patch("sdtoolplus.events.sync_ou")
async def test__mo_org_unit_only_process_sd_units(
    mock_sync_ou: AsyncMock,
    graphql_client: GraphQLClient,
    base_tree_builder: TestingCreateOrgUnitOrgUnitCreate,
    org_unit_type: UUID,
    org_unit_levels: dict[str, OrgUnitLevelUUID],
) -> None:
    """
    Make sure we only process the unit event if we are in the SD part
    of the OU tree.
    """
    org_unit_uuid = uuid4()

    # Create non-SD org unit
    org_unit_uuid = (
        await graphql_client.create_org_unit(
            input=OrganisationUnitCreateInput(
                uuid=org_unit_uuid,
                validity=RAValidityInput(from_=datetime(2000, 1, 1), to=None),
                name="Not an SD unit",
                user_key="II-make-sure-we-would-pass-the-hyphen-filter",
                parent=None,
                org_unit_type=org_unit_type,
                org_unit_level=org_unit_levels["Afdelings-niveau"],
            )
        )
    ).uuid

    # Ensure the unit is created before we assert
    @retry()
    async def verify() -> None:
        mo_org_unit = await graphql_client.get_unit(org_unit_uuid)
        assert mo_org_unit.objects

    await verify()

    mock_sync_ou.assert_not_awaited()


@pytest.mark.envvar(
    {
        "UNKNOWN_UNIT": str(UNKNOWN_UNIT),
        "APPLY_NY_LOGIC": "false",
        "ELEVATE_MANAGERS": "true",
        "EVENT_BASED_SYNC": "true",
        "DISABLE_MO_OU_EVENTS": "true",
        "DISABLE_MO_PERSON_EVENTS": "true",
        "PREFIX_ENGAGEMENT_USER_KEYS": "true",
    }
)
@pytest.mark.integration_test
async def test_mo_manager_event_triggers_engagement_elevation(
    respx_mock: MockRouter,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    base_tree_builder: TestingCreateOrgUnitOrgUnitCreate,
    job_function_1234: UUID,
) -> None:
    """
    Verify that a MO manager event re-triggers engagement sync so the
    elevate-managers OU strategy moves the engagement to the manager's unit.
    """
    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")

    t1 = datetime(2000, 1, 1, tzinfo=tz)

    person_cpr = CPRNumber("0101011234")
    employment_identifier = "12345"
    engagement_user_key = f"II-{employment_identifier}"

    dep2_uuid = UUID("20000000-0000-0000-0000-000000000000")  # Manager unit
    dep3_uuid = UUID("30000000-0000-0000-0000-000000000000")  # SD eng unit

    # Configure SD API GetEmploymentChanged mock — engagement is in dep3 in SD
    respx_mock.get(
        f"https://service.sd.dk/sdws/GetEmploymentChanged20111201?InstitutionIdentifier=II&PersonCivilRegistrationIdentifier={person_cpr}&EmploymentIdentifier={employment_identifier}&ActivationDate=01.01.0001&DeactivationDate=31.12.9999&DepartmentIndicator=True&EmploymentStatusIndicator=True&ProfessionIndicator=True&SalaryAgreementIndicator=False&SalaryCodeGroupIndicator=False&WorkingTimeIndicator=True&UUIDIndicator=True"
    ).respond(
        content_type="text/xml;charset=UTF-8",
        content=f"""<?xml version="1.0" encoding="UTF-8"?>
        <GetEmploymentChanged20111201 creationDateTime="2025-03-10T13:50:06">
          <RequestStructure>
            <InstitutionIdentifier>II</InstitutionIdentifier>
            <PersonCivilRegistrationIdentifier>{person_cpr}</PersonCivilRegistrationIdentifier>
            <ActivationDate>2000-01-01</ActivationDate>
            <DeactivationDate>2006-12-31</DeactivationDate>
            <DepartmentIndicator>true</DepartmentIndicator>
            <EmploymentStatusIndicator>true</EmploymentStatusIndicator>
            <ProfessionIndicator>true</ProfessionIndicator>
            <SalaryAgreementIndicator>false</SalaryAgreementIndicator>
            <SalaryCodeGroupIndicator>false</SalaryCodeGroupIndicator>
            <WorkingTimeIndicator>false</WorkingTimeIndicator>
            <UUIDIndicator>true</UUIDIndicator>
          </RequestStructure>
          <Person>
            <PersonCivilRegistrationIdentifier>{person_cpr}</PersonCivilRegistrationIdentifier>
            <Employment>
              <EmploymentIdentifier>{employment_identifier}</EmploymentIdentifier>
              <EmploymentDate>2000-01-01</EmploymentDate>
              <AnniversaryDate>2000-01-01</AnniversaryDate>
              <EmploymentDepartment>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <DepartmentIdentifier>dep3</DepartmentIdentifier>
                <DepartmentUUIDIdentifier>{dep3_uuid}</DepartmentUUIDIdentifier>
              </EmploymentDepartment>
              <Profession>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <JobPositionIdentifier>1234</JobPositionIdentifier>
                <EmploymentName>name1</EmploymentName>
                <AppointmentCode>0</AppointmentCode>
              </Profession>
              <EmploymentStatus>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <EmploymentStatusCode>1</EmploymentStatusCode>
              </EmploymentStatus>
              <WorkingTime>
                <ActivationDate>2000-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <OccupationRate>1.0000</OccupationRate>
                <SalaryRate>1.0000</SalaryRate>
                <SalariedIndicator>true</SalariedIndicator>
                <FullTimeIndicator>true</FullTimeIndicator>
              </WorkingTime>
            </Employment>
          </Person>
        </GetEmploymentChanged20111201>
        """,
    )

    # Create person and engagement at dep3 (matching SD).
    person_uuid = (
        await graphql_client.create_person(
            input=EmployeeCreateInput(
                cpr_number=person_cpr,
                given_name="Chuck",
                surname="Norris",
            )
        )
    ).uuid

    engagement_types = await get_engagement_types(graphql_client)
    eng_uuid = (
        await graphql_client.create_engagement(
            EngagementCreateInput(
                user_key=engagement_user_key,
                validity=timeline_interval_to_mo_validity(t1, POSITIVE_INFINITY),
                extension_4="dep3",
                extension_5=str(dep3_uuid),
                person=person_uuid,
                org_unit=dep3_uuid,
                engagement_type=engagement_types[EngType.MONTHLY_FULL_TIME],
                job_function=job_function_1234,
            )
        )
    ).uuid

    # Wait for the initial engagement event to be processed. With no manager
    # yet, the engagement should stay at dep3 (matches SD).
    @retry()
    async def wait_for_initial_sync() -> None:
        mo_engagement = await graphql_client.get_engagement_timeline(
            get_engagement_filter(
                person=person_uuid,
                user_key=engagement_user_key,
                from_date=None,
                to_date=None,
            )
        )
        assert len(mo_engagement.objects) == 1

    await wait_for_initial_sync()

    # Act

    # Create a manager at dep2 linked to the engagement. This emits a MO
    # manager event that the _mo_manager handler picks up and turns into an
    # engagement refresh, which in turn re-runs the elevate-managers strategy.
    manager_level = await get_class(graphql_client, "manager_level", "afdelingsleder")
    manager_type = await get_class(graphql_client, "manager_type", "leder")
    responsibility = await get_class(graphql_client, "responsibility", "personale")

    await graphql_client._testing__create_manager(
        ManagerCreateInput(
            user_key=employment_identifier,
            person=person_uuid,
            responsibility=[responsibility],
            engagement=eng_uuid,
            org_unit=dep2_uuid,
            manager_level=manager_level,
            manager_type=manager_type,
            validity=timeline_interval_to_mo_validity(t1, POSITIVE_INFINITY),
        )
    )

    # Assert

    # Verify the engagement is elevated to the manager's unit (dep2).
    @retry()
    async def verify() -> None:
        mo_engagement = await graphql_client.get_engagement_timeline(
            get_engagement_filter(
                person=person_uuid,
                user_key=engagement_user_key,
                from_date=None,
                to_date=None,
            )
        )

        interval_1 = one(one(mo_engagement.objects).validities)

        assert interval_1.validity.from_ == t1
        assert mo_end_to_timeline_end(interval_1.validity.to) == POSITIVE_INFINITY
        assert interval_1.org_unit_uuid == dep2_uuid
        assert interval_1.extension_4 == "dep2"
        assert interval_1.extension_5 == str(dep3_uuid)

    await verify()


@pytest.mark.parametrize(
    "d, status_code, retry_after",
    [
        ("2025-01-01T21:30:00+01:00", 200, None),
        ("2025-01-01T22:30:00+01:00", 503, "27300"),
        ("2025-01-01T00:30:00+01:00", 503, "20100"),
        ("2025-01-01T06:30:00+01:00", 200, None),
    ],
)
async def test_retry_after_when_sd_api_is_closed(
    d: str,
    status_code: int,
    retry_after: str | None,
) -> None:
    """Tests the sd_api_open dependency in isolation."""
    app = FastAPI()

    @app.post("/endpoint", dependencies=[Depends(sd_api_open)])
    async def endpoint() -> None:
        return

    with TestClient(app) as client:
        with freeze_time(d):
            r = client.post("/endpoint")
            assert r.status_code == status_code
            assert r.headers.get("Retry-After") == retry_after


@pytest.mark.parametrize(
    "event_type, expected",
    [
        (
            "EMPLOYMENT_CHANGED",
            EventSendInput(
                namespace="sd",
                routing_key="person-employment",
                subject=PersonAndEmploymentGraphQLEvent(
                    institution_identifier="XY",
                    employment_identifier="12345",
                    cpr="1234567890",
                ).json(),
            ),
        ),
        (
            "EMPLOYMENT_CONTACT_INFO_CHANGED",
            EventSendInput(
                namespace="sd",
                routing_key="person-employment",
                subject=PersonAndEmploymentGraphQLEvent(
                    institution_identifier="XY",
                    employment_identifier="12345",
                    cpr="1234567890",
                ).json(),
            ),
        ),
    ],
)
async def test_process_sd_amqp_employment_event(
    event_type: str,
    expected: EventSendInput,
) -> None:
    # TODO: write an integration test!

    # Arrange
    message_bytes = json.dumps(
        {
            "id": "965cbb12-2329-451a-9e1f-0cb7ddf9c4b1",
            "eventType": event_type,
            "instCode": "XY",
            "tjnr": "12345",
            "cpr": "1234567890",
        }
    ).encode("utf-8")

    message = MagicMock()
    message.body = message_bytes

    mock_gql_client = AsyncMock()

    # Act
    await process_sd_amqp_employment_event(message, mock_gql_client)

    # Assert
    mock_gql_client.send_event.assert_awaited_once_with(input=expected)


@pytest.mark.envvar(
    {
        "APPLY_NY_LOGIC": "false",
        "UNKNOWN_UNIT": str(UNKNOWN_UNIT),
        "EVENT_BASED_SYNC": "true",
        # The dedicated SD broker (sd-amqp) is not available in CI, so point the
        # SD AMQP integration at the os2mo message broker instead.
        "SD_AMQP__URL": SD_AMQP_URL,
        # We only want to exercise the SD AMQP -> SD person/employment event
        # flow, so disable the MO event listeners.
        "DISABLE_MO_EVENTS": "true",
    }
)
@pytest.mark.integration_test
async def test_sd_employment_amqp_event_is_processed(
    sd_amqp_queues: None,
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    base_tree_builder: TestingCreateOrgUnitOrgUnitCreate,
    job_function_1234: UUID,
    respx_mock: MockRouter,
) -> None:
    """
    Send an SD employment event via the SD AMQP `employment-events` queue and
    assert that it is processed correctly.

    The application consumes the AMQP message, converts it to an MO GraphQL
    "person-employment" event, which in turn triggers a sync of both the person
    and the engagement in MO.
    """
    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)

    cpr = "0101011234"
    emp_id = "12345"
    dep1_uuid = UUID("10000000-0000-0000-0000-000000000000")

    today_sd_format = date.strftime(date.today(), "%Y-%m-%d")
    today_url_format = date.strftime(date.today(), "%d.%m.%Y")

    # The person does not exist in MO yet
    mo_person_before = await graphql_client.get_person(cpr=CPRNumber(cpr))
    assert mo_person_before.objects == []

    # Configure the SD API GetPerson mock
    respx_mock.get(
        f"https://service.sd.dk/sdws/GetPerson20111201?InstitutionIdentifier=II&EffectiveDate={today_url_format}&PersonCivilRegistrationIdentifier={cpr}&StatusActiveIndicator=True&StatusPassiveIndicator=True&ContactInformationIndicator=True&PostalAddressIndicator=True"
    ).respond(
        content_type="text/xml;charset=UTF-8",
        content=f"""<?xml version="1.0" encoding="UTF-8" ?>
            <GetPerson20111201 creationDateTime="2025-04-09T09:47:55">
                <RequestStructure>
                    <InstitutionIdentifier>II</InstitutionIdentifier>
                    <PersonCivilRegistrationIdentifier>{cpr}</PersonCivilRegistrationIdentifier>
                    <EffectiveDate>{today_sd_format}</EffectiveDate>
                    <StatusActiveIndicator>true</StatusActiveIndicator>
                    <StatusPassiveIndicator>true</StatusPassiveIndicator>
                    <ContactInformationIndicator>false</ContactInformationIndicator>
                    <PostalAddressIndicator>false</PostalAddressIndicator>
                </RequestStructure>
                <Person>
                    <PersonCivilRegistrationIdentifier>{cpr}</PersonCivilRegistrationIdentifier>
                    <PersonGivenName>Chuck</PersonGivenName>
                    <PersonSurnameName>Norris</PersonSurnameName>
                    <Employment>
                        <EmploymentIdentifier>{emp_id}</EmploymentIdentifier>
                    </Employment>
                </Person>
            </GetPerson20111201>
        """,
    )

    # Configure the SD API GetEmploymentChanged mock (a single active interval
    # in dep1)
    respx_mock.get(
        f"https://service.sd.dk/sdws/GetEmploymentChanged20111201?InstitutionIdentifier=II&PersonCivilRegistrationIdentifier={cpr}&EmploymentIdentifier={emp_id}&ActivationDate=01.01.0001&DeactivationDate=31.12.9999&DepartmentIndicator=True&EmploymentStatusIndicator=True&ProfessionIndicator=True&SalaryAgreementIndicator=False&SalaryCodeGroupIndicator=False&WorkingTimeIndicator=True&UUIDIndicator=True"
    ).respond(
        content_type="text/xml;charset=UTF-8",
        content=f"""<?xml version="1.0" encoding="UTF-8"?>
        <GetEmploymentChanged20111201 creationDateTime="2025-03-10T13:50:06">
          <RequestStructure>
            <InstitutionIdentifier>II</InstitutionIdentifier>
            <PersonCivilRegistrationIdentifier>{cpr}</PersonCivilRegistrationIdentifier>
            <ActivationDate>2001-01-01</ActivationDate>
            <DeactivationDate>9999-12-31</DeactivationDate>
            <DepartmentIndicator>true</DepartmentIndicator>
            <EmploymentStatusIndicator>true</EmploymentStatusIndicator>
            <ProfessionIndicator>true</ProfessionIndicator>
            <SalaryAgreementIndicator>false</SalaryAgreementIndicator>
            <SalaryCodeGroupIndicator>false</SalaryCodeGroupIndicator>
            <WorkingTimeIndicator>false</WorkingTimeIndicator>
            <UUIDIndicator>true</UUIDIndicator>
          </RequestStructure>
          <Person>
            <PersonCivilRegistrationIdentifier>{cpr}</PersonCivilRegistrationIdentifier>
            <Employment>
              <EmploymentIdentifier>{emp_id}</EmploymentIdentifier>
              <EmploymentDate>2001-01-01</EmploymentDate>
              <AnniversaryDate>2001-01-01</AnniversaryDate>
              <EmploymentDepartment>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <DepartmentIdentifier>dep1</DepartmentIdentifier>
                <DepartmentUUIDIdentifier>{str(dep1_uuid)}</DepartmentUUIDIdentifier>
              </EmploymentDepartment>
              <Profession>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <JobPositionIdentifier>1234</JobPositionIdentifier>
                <EmploymentName>name1</EmploymentName>
                <AppointmentCode>0</AppointmentCode>
              </Profession>
              <EmploymentStatus>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <EmploymentStatusCode>1</EmploymentStatusCode>
              </EmploymentStatus>
              <WorkingTime>
                <ActivationDate>2001-01-01</ActivationDate>
                <DeactivationDate>9999-12-31</DeactivationDate>
                <OccupationRate>1.0000</OccupationRate>
                <SalaryRate>1.0000</SalaryRate>
                <SalariedIndicator>true</SalariedIndicator>
                <FullTimeIndicator>true</FullTimeIndicator>
              </WorkingTime>
            </Employment>
          </Person>
        </GetEmploymentChanged20111201>
        """,
    )

    # Act: publish an SD employment event to the SD AMQP `employment-events`
    # queue (the same queue the application consumes from)
    connection = await aio_pika.connect(SD_AMQP_URL)
    try:
        channel = await connection.channel()
        await channel.default_exchange.publish(
            aio_pika.Message(
                body=json.dumps(
                    {
                        "id": str(uuid4()),
                        "eventType": "Employment",
                        "instCode": "II",
                        "tjnr": emp_id,
                        "cpr": cpr,
                    }
                ).encode("utf-8")
            ),
            routing_key="employment-events",
        )
    finally:
        await connection.close()

    # Assert: the person and the engagement are eventually synced to MO
    @retry()  # type: ignore[no-redef]
    async def verify() -> None:
        mo_person = await graphql_client.get_person_timeline(
            filter=EmployeeFilter(
                cpr_numbers=[CPRNumber(cpr)], from_date=None, to_date=None
            )
        )
        person = one(mo_person.objects)
        assert one(person.validities).given_name == "Chuck"

        mo_engagement = await graphql_client.get_engagement_timeline(
            get_engagement_filter(
                person=person.uuid,
                user_key=emp_id,
                from_date=None,
                to_date=None,
            )
        )
        validity = one(one(mo_engagement.objects).validities)
        assert validity.validity.from_ == t1
        assert validity.org_unit_uuid == dep1_uuid

    await verify()
