# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import date
from datetime import datetime
from datetime import time
from datetime import timedelta
from uuid import UUID
from zoneinfo import ZoneInfo

import pytest
from httpx import AsyncClient
from more_itertools import one
from respx import MockRouter

from sdtoolplus.autogenerated_graphql_client.input_types import EmployeeCreateInput
from sdtoolplus.autogenerated_graphql_client.input_types import EmployeeFilter
from sdtoolplus.depends import GraphQLClient

CPR = "0101011234"

EMP_ID = "12345"
TODAY_SD_FORMAT = date.strftime(date.today(), "%Y-%m-%d")
TODAY_URL_FORMAT = date.strftime(date.today(), "%d.%m.%Y")
GETPERSON_URL = f"https://service.sd.dk/sdws/GetPerson20111201?InstitutionIdentifier=II&EffectiveDate={TODAY_URL_FORMAT}&PersonCivilRegistrationIdentifier={CPR}&StatusActiveIndicator=True&StatusPassiveIndicator=False&ContactInformationIndicator=True&PostalAddressIndicator=True"

SD_RESP = f"""<?xml version="1.0" encoding="UTF-8" ?>
    <GetPerson20111201 creationDateTime="2025-04-09T09:47:55">
        <RequestStructure>
            <InstitutionIdentifier>II</InstitutionIdentifier>
            <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
            <EffectiveDate>{TODAY_SD_FORMAT}</EffectiveDate>
            <StatusActiveIndicator>true</StatusActiveIndicator>
            <StatusPassiveIndicator>false</StatusPassiveIndicator>
            <ContactInformationIndicator>false</ContactInformationIndicator>
            <PostalAddressIndicator>false</PostalAddressIndicator>
        </RequestStructure>
        <Person>
            <PersonCivilRegistrationIdentifier>0101011234</PersonCivilRegistrationIdentifier>
            <PersonGivenName>Chuck</PersonGivenName>
            <PersonSurnameName>Norris</PersonSurnameName>
            <Employment>
                <EmploymentIdentifier>{EMP_ID}</EmploymentIdentifier>
            </Employment>
        </Person>
    </GetPerson20111201>
"""


@pytest.mark.integration_test
async def test_person_not_in_sd(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    respx_mock: MockRouter,
):
    """
    We are testing this scenario:
    The called person dosn't exist in SD


    """
    # Arrange

    cpr = "0101010101"
    get_person_url = f"https://service.sd.dk/sdws/GetPerson20111201?InstitutionIdentifier=II&EffectiveDate={TODAY_URL_FORMAT}&PersonCivilRegistrationIdentifier={cpr}&StatusActiveIndicator=True&StatusPassiveIndicator=False&ContactInformationIndicator=True&PostalAddressIndicator=True"

    respx_mock.get(get_person_url).respond(
        content_type="text/xml;charset=UTF-8",
        content="""
        <Envelope>
            <Body>
                <Fault>
                    <faultcode>soapenv:soapenvClient.ParameterError</faultcode>
                    <faultstring>
                        The stated PersonCivilRegistrationIdentifier '0101010101' does not exist.
                    </faultstring>
                    <faultactor>
                        dk.eg.sd.loen.webservices.web.sdws.BusinessHandler.qm.GetPerson20111201BO
                    </faultactor>
                    <detail>
                        <string>
                            Missing or invalid parameter from client: "The stated PersonCivilRegistrationIdentifier '0101010101' does not exist."
                        </string>
                    </detail>
                </Fault>
            </Body>
        </Envelope>
        """,
    )

    # Act
    r = await test_client.post(
        "/timeline/sync/person",
        json={
            "institution_identifier": "II",
            "cpr": cpr,
        },
    )

    # Assert
    assert r.status_code == 404


@pytest.mark.integration_test
async def test_person_create_new(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    respx_mock: MockRouter,
):
    """
    We are testing this scenario:
    A person dosnt exist in MO and is created


    MO (givenname, surname)
    SD (givenname, surname)              |-----------------Chuck Norris--------------------------------------

    "Assert"                  |----1----||--2-----------------------------------------------------------------
    intervals
    """
    # Arrange
    # Ensure the person doesn't exist yet
    mo_person_before = await graphql_client.get_person(cpr=CPR)

    assert mo_person_before.objects == []
    respx_mock.get(GETPERSON_URL).respond(
        content_type="text/xml;charset=UTF-8",
        content=SD_RESP,
    )

    # Act
    r = await test_client.post(
        "/timeline/sync/person",
        json={
            "institution_identifier": "II",
            "cpr": CPR,
        },
    )

    # Assert
    assert r.status_code == 200
    # Fetch person from MO and verify it has the correct data
    mo_person = await graphql_client.get_person_validities(
        filter=EmployeeFilter(cpr_numbers=[CPR])
    )
    mo_objects = one(mo_person.objects)
    assert isinstance(mo_objects.uuid, UUID)

    mo_validities = one(mo_objects.validities)
    assert mo_validities.cpr_number == CPR
    assert mo_validities.given_name == "Chuck"
    assert mo_validities.surname == "Norris"
    assert mo_validities.validity.to is None
    assert mo_validities.validity.from_ == datetime(
        1901, 1, 1, tzinfo=ZoneInfo("Europe/Copenhagen")
    )


@pytest.mark.integration_test
async def test_person_update(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    respx_mock: MockRouter,
):
    """
    We are testing this scenario:
    A person exists in MO but with the wrong name. Test that the name is updated in MO.


    MO (givenname, surname)   |-------------------Buck Lorris-----------------------------------------------------
    SD (givenname, surname)              |-----------------Chuck Norris-------------------------------------------

    "Assert"                  |----1----||--2--------------------------------------------------------------
    intervals
    """
    # Arrange
    await graphql_client.create_person(
        EmployeeCreateInput(
            cpr_number=CPR,
            given_name="Buck",
            surname="Lorris",
        )
    )

    respx_mock.get(GETPERSON_URL).respond(
        content_type="text/xml;charset=UTF-8",
        content=SD_RESP,
    )

    # Act
    r = await test_client.post(
        "/timeline/sync/person",
        json={
            "institution_identifier": "II",
            "cpr": CPR,
        },
    )

    # Assert
    assert r.status_code == 200

    mo_timeline = await graphql_client.get_person_validities(
        filter=EmployeeFilter(cpr_numbers=[CPR], from_date=None, to_date=None)
    )
    validities = one(mo_timeline.objects).validities

    assert len(validities) == 2
    before, after = validities

    assert before.given_name == "Buck"
    assert before.surname == "Lorris"
    assert before.validity.from_ == datetime(
        1901, 1, 1, tzinfo=ZoneInfo("Europe/Copenhagen")
    )
    midnight = datetime.combine(
        datetime.today(), time.min, tzinfo=ZoneInfo("Europe/Copenhagen")
    )
    assert before.validity.to == midnight - timedelta(days=1)

    assert after.given_name == "Chuck"
    assert after.surname == "Norris"
    assert after.validity.from_ == midnight
    assert after.validity.to is None
