# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from sdtoolplus.autogenerated_graphql_client import GraphQLClient
from fastramqpi.config import ClientSettings
from fastramqpi.main import construct_mo_client

from sdtoolplus.config import get_settings


def get_gql_client() -> GraphQLClient:
    settings = get_settings()
    client_settings = ClientSettings(
        mo_url=settings.fastramqpi.mo_url,
        client_id=settings.fastramqpi.client_id,
        client_secret=settings.fastramqpi.client_secret,
        auth_server=settings.fastramqpi.auth_server,
        auth_realm=settings.fastramqpi.auth_realm,
    )

    mo_client = construct_mo_client(client_settings)

    gql_client = GraphQLClient(
        url=f"{settings.fastramqpi.mo_url}/graphql/v25",
        http_client=mo_client,
    )

    return gql_client
