# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import asyncio
import csv
from pathlib import Path

# This script is currently necessary due to performance issues with the engagements
# refresh mutator, i.e. calling /timeline/sync/engagement/all/mo will take forever to
# complete.
import click
import structlog
from more_itertools import last

from scripts.common import get_gql_client
from sdtoolplus.autogenerated_graphql_client import EventSendInput
from sdtoolplus.autogenerated_graphql_client import GraphQLClient
from sdtoolplus.models import EmploymentGraphQLEvent

ENGAGEMENT_SYNC_URL = "http://localhost:8000/timeline/sync/engagement"

logger = structlog.stdlib.get_logger()


async def sync_all_mo_engagements(
    gql_client: GraphQLClient, engagements_csv_file: Path, priority: int
) -> None:
    with open(engagements_csv_file, newline="") as fp:
        reader = csv.DictReader(fp)
        for i, row in enumerate(reader):
            institution_identifier, employment_identifier = row["user_key"].split("-")
            cpr = last(row["cpr"].split(":"))

            logger.info(
                "Queuing engagement",
                institution_identifier=institution_identifier,
                cpr=cpr,
                employment_identifier=employment_identifier,
                employee_uuid=row["employee"],
                counter=i,
            )

            await gql_client.send_event(
                input=EventSendInput(
                    namespace="sd",
                    routing_key="employment",
                    subject=EmploymentGraphQLEvent(
                        institution_identifier=institution_identifier,
                        cpr=cpr,
                        employment_identifier=employment_identifier,
                    ).json(),
                    priority=priority,
                )
            )


@click.command()
@click.option(
    "--engagements-csv-file",
    type=click.Path(exists=True),
    default=Path("/tmp/engagements.csv"),
    help="Path to the CSV file containing the engagements to sync",
)
@click.option(
    "--priority",
    type=click.INT,
    default=20_000,
    help="The queue priority",
)
def main(
    engagements_csv_file: Path,
    priority: int,
) -> None:
    logger.info("Script started")

    gql_client = get_gql_client()
    asyncio.run(sync_all_mo_engagements(gql_client, engagements_csv_file, priority))

    logger.info("Script finished")


if __name__ == "__main__":
    main()
