# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import asyncio
import datetime
import re
from typing import Any
from uuid import UUID

import structlog
from fastapi import APIRouter
from fastapi import Response
from fastramqpi.os2mo_dar_client import AsyncDARClient
from more_itertools import one
from sdclient.client import SDClient
from sdclient.exceptions import SDCallError
from sdclient.exceptions import SDRootElementNotFound
from sdclient.requests import GetDepartmentRequest
from sdclient.responses import Department
from starlette.status import HTTP_200_OK

from . import depends
from .addresses import AddressFixer
from .app import App
from .autogenerated_graphql_client import ClassFilter
from .autogenerated_graphql_client import EngagementFilter
from .autogenerated_graphql_client import EventSendInput
from .autogenerated_graphql_client import FacetFilter
from .db.rundb import Status
from .db.rundb import delete_last_run
from .db.rundb import get_status
from .db.rundb import run_db_end_operations
from .db.rundb import run_db_start_operations
from .exceptions import UnknownNYLevel
from .job_positions import sync_professions
from .mo_class import MOOrgUnitLevelMap
from .models import OrgGraphQLEvent
from .models import PersonAndEmploymentGraphQLEvent
from .sd.person import get_all_sd_persons
from .sd.person import get_sd_person_engagements
from .tree_tools import tree_as_string

logger = structlog.stdlib.get_logger()

router = APIRouter()


@router.get("/tree/mo")
async def print_mo_tree(settings: depends.Settings) -> str:
    """
    For debugging problems. Prints the part of the MO tree that
    should be compared to the SD tree.
    """
    sdtoolplus: App = App(settings)
    mo_tree = sdtoolplus.get_mo_tree()
    return tree_as_string(mo_tree)


@router.get("/tree/sd")
async def print_sd_tree(settings: depends.Settings) -> str:
    """
    For debugging problems. Prints the SD tree.
    """
    sdtoolplus: App = App(settings)
    mo_org_unit_level_map = MOOrgUnitLevelMap(sdtoolplus.session)
    sd_tree = await sdtoolplus.get_sd_tree(mo_org_unit_level_map)
    return tree_as_string(sd_tree)


@router.get("/rundb/status")
async def rundb_get_status(engine: depends.Engine) -> int:
    """
    Get the RunDB status and return a job-runner.sh (curl) friendly integer
    status.

    Returns:
        0 if status is "completed", 1 if status is "running" and 3 in case of
        an error.
    """
    try:
        status = await get_status(engine)
        return 0 if status == Status.COMPLETED else 1
    except Exception:
        return 3


@router.post("/rundb/delete-last-run")
async def rundb_delete_last_run(engine: depends.Engine):
    await delete_last_run(engine)
    return {"msg": "Last run deleted"}


@router.post("/job-functions/sync")
async def sync_job_functions(
    sd_client: depends.SDClient,
    graphql_client: depends.GraphQLClient,
    institution_identifier: str,
    force_class_start_date: datetime.date | None = None,
) -> None:
    await sync_professions(
        sd_client, graphql_client, institution_identifier, force_class_start_date
    )


@router.post("/trigger", status_code=HTTP_200_OK)
async def trigger(
    settings: depends.Settings,
    engine: depends.Engine,
    response: Response,
    org_unit: UUID | None = None,
    inst_id: str | None = None,
    dry_run: bool = False,
) -> list[dict] | dict:
    logger.info("Starting run", org_unit=str(org_unit), dry_run=dry_run)

    run_db_start_operations_resp = await run_db_start_operations(
        engine, dry_run, response
    )
    if run_db_start_operations_resp is not None:
        return run_db_start_operations_resp

    sdtoolplus: App = App(settings, inst_id)

    results: list[dict] = [
        {
            "type": mutation.__class__.__name__,
            "unit": repr(org_unit_node),
            "mutation_result": str(result),
        }
        async for org_unit_node, mutation, result in sdtoolplus.execute(
            org_unit=org_unit, dry_run=dry_run
        )
    ]
    logger.info("Finished adding or updating org unit objects")

    # Send email notifications for illegal moves
    if settings.email_notifications_enabled and not dry_run:
        sdtoolplus.send_email_notification()

    await run_db_end_operations(engine, dry_run)
    logger.info("Run completed!")

    return results


@router.post("/trigger/addresses", status_code=HTTP_200_OK)
async def trigger_addresses(
    settings: depends.Settings,
    engine: depends.Engine,
    response: Response,
    gql_client: depends.GraphQLClient,
    org_unit: UUID | None = None,
    inst_id: str | None = None,
    dry_run: bool = False,
) -> list[dict] | dict:
    logger.info("Starting address run", org_unit=str(org_unit), dry_run=dry_run)

    run_db_start_operations_resp = await run_db_start_operations(
        engine, dry_run, response
    )
    if run_db_start_operations_resp is not None:
        return run_db_start_operations_resp

    addr_fixer = AddressFixer(
        gql_client,
        SDClient(
            settings.sd_username,
            settings.sd_password.get_secret_value(),
        ),
        AsyncDARClient(),
        settings,
        inst_id if inst_id is not None else settings.sd_institution_identifier,
    )

    results: list[dict] = [
        {
            "address_operation": operation.value,
            "address_type": addr.address_type.user_key,
            "unit": repr(org_unit_node),
            "address": addr.value,
        }
        async for operation, org_unit_node, addr in addr_fixer.fix_addresses(
            org_unit, dry_run
        )
    ]
    logger.info("Finished adding or updating org unit objects")

    await run_db_end_operations(engine, dry_run)
    logger.info("Run completed!")

    return results


@router.post("/timeline/sync/person/all")
async def sync_all_persons(
    sd_client: depends.SDClient,
    graphql_client: depends.GraphQLClient,
    institution_identifier: str,
    sync_active_persons: bool = True,
    sync_passive_persons: bool = False,
) -> dict:
    """
    Sync all persons in SD
    """
    logger.info("Syncing all SD persons")

    sd_persons = await get_all_sd_persons(
        sd_client=sd_client,
        institution_identifier=institution_identifier,
        effective_date=datetime.date.today(),
        sync_active_persons=sync_active_persons,
        sync_passive_persons=sync_passive_persons,
    )

    events = [
        EventSendInput(
            namespace="sd",
            routing_key="person-and-employment",
            subject=PersonAndEmploymentGraphQLEvent(
                institution_identifier=institution_identifier,
                cpr=person.cpr,
            ).json(),
        )
        for person in sd_persons
    ]
    logger.info(
        "Syncing persons",
        events=len(events),
    )
    for e in events:
        await graphql_client.send_event(input=e)

    logger.info(f"Done queueing sync all SD persons in {institution_identifier}")

    return {"msg": f"{len(events)} person events queued"}


@router.post("/timeline/sync/person-and-engagement/all/sd", status_code=HTTP_200_OK)
async def full_timeline_sync_sd_engagements(
    sd_client: depends.SDClient,
    gql_client: depends.GraphQLClient,
    institution_identifier: str,
    sync_active_persons: bool = True,
    sync_passive_persons: bool = False,
) -> dict:
    """
    Sync engagements of all SD persons, i.e.

    1) Read all persons from SD
    2) Loop through these and for each get a list of their SD employments
    3) Loop through the list of SD employments and queue these for sync
    """
    logger.info(f"Syncing all SD employments in {institution_identifier}")

    sd_persons = await get_all_sd_persons(
        sd_client=sd_client,
        institution_identifier=institution_identifier,
        effective_date=datetime.date.today(),
        sync_active_persons=sync_active_persons,
        sync_passive_persons=sync_passive_persons,
    )

    error_cprs: list[str] = []
    for person in sd_persons:
        if person.cpr.endswith("0000"):
            continue
        try:
            res = await get_sd_person_engagements(
                sd_client=sd_client,
                institution_identifier=institution_identifier,
                cpr=person.cpr,
            )
        except SDRootElementNotFound:
            logger.info(
                "Person could not be found in sd",
                institution_identifier=institution_identifier,
                person=person,
            )
            continue
        except SDCallError:
            logger.error("SD call failed", cpr=person.cpr)
            error_cprs.append(person.cpr)
            continue

        logger.info("Found engagements", engagements=res)

        for e in one(res.Person).Employment:
            event = EventSendInput(
                namespace="sd",
                routing_key="person-and-employment",
                subject=PersonAndEmploymentGraphQLEvent(
                    institution_identifier=institution_identifier,
                    cpr=person.cpr,
                    employment_identifier=e.EmploymentIdentifier,
                ).json(),
            )
            await gql_client.send_event(input=event)

    logger.info(
        f"Done queueing sync for all SD employments in {institution_identifier}"
    )

    return {"msg": "success", "error_cprs": error_cprs}


@router.post("/timeline/sync/engagement/all/mo", status_code=HTTP_200_OK)
async def full_timeline_sync_mo_engagements(
    gql_client: depends.GraphQLClient,
    settings: depends.Settings,
    engagement_uuid: UUID | None = None,
    limit: int = 500,
    priority: int = 20_000,
) -> dict:
    """
    Sync all engagements in MO (and only the ones that already exist in MO).
    """
    logger.info("Syncing all MO engagements")

    # Get actor UUID for application
    me = await gql_client.get_actor()

    # Refresh all MO engagements
    eng_filter: dict[str, Any] = {
        "engagement_type": ClassFilter(
            facet=FacetFilter(user_keys=["engagement_type"]),
            user_keys=[
                # TODO: remove when new integration is deployed everywhere
                # User keys from the old SD integration
                "timeløn",
                "månedsløn",
            ]
            + settings.engagement_types_to_process,
        ),
        "from_date": None,
        "to_date": None,
    }
    if engagement_uuid is not None:
        eng_filter["uuids"] = [engagement_uuid]

    next_cursor = None
    engagements_refreshed = 0
    while True:
        batch = await gql_client.refresh_engagements(
            cursor=next_cursor,
            limit=limit,
            filter=EngagementFilter(**eng_filter),
            owner=me.actor.uuid,
            priority=priority,
        )
        next_cursor = batch.page_info.next_cursor

        engagements_refreshed += len(batch.objects)
        logger.info("Engagements refreshed", n=engagements_refreshed)

        if next_cursor is None:
            break

    logger.info("Done queueing all MO engagements")

    return {"msg": "success"}


@router.post("/timeline/sync/ou/all", status_code=HTTP_200_OK)
async def full_timeline_sync_ous(
    sd_client: depends.SDClient,
    gql_client: depends.GraphQLClient,
    institution_identifier: str,
    dry_run: bool = False,
) -> dict:
    logger.info(f"Syncing all SD units in {institution_identifier}")
    # TODO: This only works when all unit_levels are integers
    ny_regex = re.compile(r"NY(\d)-niveau")

    def priority_from_level(department: Department) -> int:
        # Set priority on org_unit events such that top-level units are imported first.
        DEFAULT_PRIORITY = 10_000
        if department.DepartmentLevelIdentifier == "Afdelings-niveau":
            return DEFAULT_PRIORITY
        match = ny_regex.match(department.DepartmentLevelIdentifier)
        if not match:
            raise UnknownNYLevel()
        priority = DEFAULT_PRIORITY - int(one(match.groups()))
        return priority

    departments = await asyncio.to_thread(
        sd_client.get_department,
        GetDepartmentRequest(
            InstitutionIdentifier=institution_identifier,
            ActivationDate=datetime.datetime.now(),
            DeactivationDate=datetime.datetime.now(),
            DepartmentNameIndicator=False,
            UUIDIndicator=True,
            PostalAddressIndicator=False,
        ),
    )
    if dry_run:
        logger.info(
            f"Dry-run. Would create {len(departments.Department)} org_unit events"
        )
        return {"msg": "success"}

    events = []
    for d in departments.Department:
        try:
            priority = priority_from_level(d)
        except UnknownNYLevel:
            logger.warning(
                "Unknown NY level. Skipping...",
                org_unit=str(d.DepartmentUUIDIdentifier),
                level=d.DepartmentLevelIdentifier,
            )
            continue
        events.append(
            EventSendInput(
                namespace="sd",
                routing_key="org",
                subject=OrgGraphQLEvent(
                    institution_identifier=institution_identifier,
                    org_unit=d.DepartmentUUIDIdentifier,
                ).json(),
                priority=priority,
            )
        )

    logger.info("Syncing units", events=len(events))
    for e in events:
        await gql_client.send_event(input=e)

    logger.info(f"Done queueing sync all SD units in {institution_identifier}")
    return {"msg": f"{len(events)} OU events queued"}
