# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated
from typing import AsyncIterable
from uuid import uuid4

from fastapi import Depends
from fastramqpi.ramqp.depends import from_context
from structlog.contextvars import bound_contextvars

from sdtoolplus.autogenerated_graphql_client import GraphQLClient as _GraphQLClient

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]


async def request_id() -> AsyncIterable[None]:
    req_id = str(uuid4())
    with bound_contextvars(request_id=req_id):
        yield
