# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import structlog
from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.events import Namespace
from fastramqpi.main import FastRAMQPI
from sdclient.client import SDClient

from sdtoolplus.roots import ensure_sd_institution_units_and_unknown_unit

from .api import router as api_router
from .autogenerated_graphql_client import GraphQLClient
from .config import SDToolPlusSettings
from .db.engine import get_engine
from .events import router as events_router
from .events import sd_amqp_lifespan
from .middleware import ExceptionLoggerMiddleware
from .middleware import RequestIDMiddleware
from .minisync.api import minisync_router

logger = structlog.stdlib.get_logger()


def _configure_listeners(settings: SDToolPlusSettings) -> list[Listener]:
    listeners: list[Listener] = []
    if not settings.event_based_sync:
        return listeners
    if not settings.disable_sd_events:
        if not settings.disable_sd_ou_events:
            listeners.append(
                Listener(
                    namespace="sd",
                    user_key="org",
                    routing_key="org",
                    path="/events/sd/org",
                    # The org unit handler requeues its parent/children with priority
                    # +1/-1. We don't understand the implications of doing this in
                    # parallel.
                    parallelism=1,
                )
            )
        if not settings.disable_sd_person_engagement_events:
            listeners.append(
                Listener(
                    namespace="sd",
                    user_key="person-and-employment",
                    routing_key="person-and-employment",
                    path="/events/sd/person-and-employment",
                    parallelism=1,
                )
            )
    if not settings.disable_mo_events:
        if not settings.disable_mo_ou_events:
            listeners.append(
                Listener(
                    namespace="mo",
                    user_key="org_unit",
                    routing_key="org_unit",
                    path="/events/mo/org-unit",
                    # The org unit handler requeues its parent/children with priority
                    # +1/-1. We don't understand the implications of doing this in
                    # parallel.
                    parallelism=1,
                )
            )
        if not settings.disable_mo_person_events:
            listeners.append(
                Listener(
                    namespace="mo",
                    user_key="person",
                    routing_key="person",
                    path="/events/mo/person",
                    parallelism=1,
                )
            )
        if not settings.disable_mo_engagement_events:
            listeners.append(
                Listener(
                    namespace="mo",
                    user_key="engagement",
                    routing_key="engagement",
                    path="/events/mo/engagement",
                    parallelism=1,
                )
            )
        if settings.elevate_managers:
            listeners.append(
                Listener(
                    namespace="mo",
                    user_key="manager",
                    routing_key="manager",
                    path="/events/mo/manager",
                    parallelism=1,
                )
            )

    return listeners


def create_fastramqpi() -> FastRAMQPI:
    settings = SDToolPlusSettings()

    fastramqpi = FastRAMQPI(
        application_name="os2mo-sdtool-plus",
        settings=settings.fastramqpi,
        graphql_client_cls=GraphQLClient,
        graphql_version=25,
        graphql_events=GraphQLEvents(
            declare_namespaces=[
                Namespace(name="sd"),
            ],
            declare_listeners=_configure_listeners(settings),
        ),
    )
    fastramqpi.add_context(settings=settings)

    engine = get_engine(settings)
    fastramqpi.add_context(engine=engine)

    sd_client = SDClient(
        sd_username=settings.sd_username,
        sd_password=settings.sd_password.get_secret_value(),
        url_subpath_xml_endpoints=settings.sd_url_subpath_xml_endpoints,
        url_subpath_json_endpoints=settings.sd_url_subpath_json_endpoints,
    )
    fastramqpi.add_context(sd_client=sd_client)

    if settings.ensure_sd_institution_units:
        fastramqpi.add_lifespan_manager(
            ensure_sd_institution_units_and_unknown_unit(
                settings=settings,
                sd_client=sd_client,
                context=fastramqpi.get_context(),
            ),
            priority=1100,
        )
    if settings.sd_amqp is not None:
        fastramqpi.add_lifespan_manager(
            sd_amqp_lifespan(
                settings=settings.sd_amqp, context=fastramqpi.get_context()
            ),
            priority=1200,
        )

    app = fastramqpi.get_app()
    app.include_router(api_router)
    app.include_router(minisync_router)
    app.include_router(events_router)

    # ExceptionLoggerMiddleware must be installed before RequestIDMiddleware to
    # ensure that exception logs receive the request-id
    app.add_middleware(ExceptionLoggerMiddleware)
    app.add_middleware(RequestIDMiddleware)

    return fastramqpi


def create_app() -> FastAPI:
    fastramqpi = create_fastramqpi()
    return fastramqpi.get_app()
