# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from datetime import timedelta
from importlib import import_module
from itertools import chain, pairwise

import structlog
from more_itertools import one

from sdtoolplus.autogenerated_graphql_client import OrganisationUnitTerminateInput
from sdtoolplus.autogenerated_graphql_client import OrganisationUnitUpdateInput
from sdtoolplus.autogenerated_graphql_client import RAValidityInput
from sdtoolplus.depends import GraphQLClient
from sdtoolplus.mo_org_unit_importer import OrgUnitUUID
from sdtoolplus.models import Active, TimelineAllowSuccessive
from sdtoolplus.models import Interval
from sdtoolplus.models import Timeline
from sdtoolplus.models import UnitId
from sdtoolplus.models import UnitLevel
from sdtoolplus.models import UnitName
from sdtoolplus.models import UnitTimeline

logger = structlog.stdlib.get_logger()

# TODO: move MO specific functions to mo.py


# TODO: find a way to use a "generic" UnitTimeline as argument type and return type
def _multidiff_timeline(
    mo_timeline: UnitTimeline, diff_timeline: UnitTimeline
) -> UnitTimeline:
    timeline_fields = diff_timeline.schema()["properties"].keys()

    # TODO: refactor to use common function here and in Timeline.diff
    endpoints: list[datetime] = list(
        set(
            chain(
        (
                    i.start
                    for field in timeline_fields
                    for i in getattr(diff_timeline, field).intervals
                ),
                (
                    i.end
                    for field in timeline_fields
                    for i in getattr(diff_timeline, field).intervals
                ),
            )
        )
    )
    endpoints.sort()

    timelines = dict()
    for field in timeline_fields:
        timeline = getattr(diff_timeline, field)

        # This is all I can think of... feel free to refactor :-)
        class_name = one(timeline.__class__.schema()["definitions"].keys())
        models = import_module("sdtoolplus.models")
        interval_class = getattr(models, class_name)

        interval_list = []
        for endpoint1, endpoint2 in pairwise(endpoints):
            if all(getattr(diff_timeline, field_).entity_at(endpoint1) is None for field_ in timeline_fields):
                continue
            diff_timeline_value = timeline.entity_at(endpoint1)
            mo_timeline_value = getattr(mo_timeline, field).entity_at(endpoint1)
            interval_list.append(
                interval_class(
                    start=endpoint1,
                    end=endpoint2,
                    value=diff_timeline_value if diff_timeline_value is not None else mo_timeline_value
                )
            )

        timelines[field] = TimelineAllowSuccessive[interval_class](
            intervals=tuple(interval_list)
        )

    return diff_timeline.__class__(**timelines)


def _get_mo_validity(interval: Interval) -> RAValidityInput:
    mo_end: datetime | None = interval.end
    assert mo_end is not None
    if mo_end.replace(tzinfo=None) == datetime.max:
        mo_end = None
    else:
        mo_end = mo_end - timedelta(days=1)  # Subtract one day due to MO
    return RAValidityInput(from_=interval.start, to=mo_end)


async def update_ou_name(
    gql_client: GraphQLClient,
    org_unit: OrgUnitUUID,
    diff_timeline: Timeline[UnitName],
) -> None:
    logger.info("Update OU name in MO")

    update_intervals = tuple(
        unit_name
        for unit_name in diff_timeline.intervals
        if unit_name.value is not None
    )

    for unit_name in update_intervals:
        logger.debug("OU name update", unit_name=unit_name)
        await gql_client.update_org_unit(
            OrganisationUnitUpdateInput(
                uuid=org_unit,
                name=unit_name.value,
                validity=_get_mo_validity(unit_name),
            )
        )


async def terminate_ou(
    gql_client: GraphQLClient,
    org_unit: OrgUnitUUID,
    diff_timeline: Timeline[Active],
) -> None:
    logger.info("(Re-)terminate OU", org_unit=str(org_unit))

    termination_intervals = tuple(
        active for active in diff_timeline.intervals if active.value is None
    )
    logger.debug("Termination intervals", intervals=termination_intervals)

    for active in termination_intervals:
        mo_validity = _get_mo_validity(active)

        if mo_validity.to is not None:
            payload = OrganisationUnitTerminateInput(
                uuid=org_unit,
                from_=mo_validity.from_,
                to=mo_validity.to,
            )
        else:
            payload = OrganisationUnitTerminateInput(
                uuid=org_unit,
                # Converting from "from" to "to" due to the wierd way terminations in MO work
                to=mo_validity.from_ - timedelta(days=1),
            )

        await gql_client.terminate_org_unit(payload)


async def update_ou(
    gql_client: GraphQLClient,
    org_unit: OrgUnitUUID,
    sd_unit_timeline: UnitTimeline,
    mo_unit_timeline: UnitTimeline,
    dry_run: bool,
) -> None:
    logger.info("Update OU in MO", org_unit=str(org_unit))

    diff = UnitTimeline(
        active=sd_unit_timeline.active.diff(mo_unit_timeline.active),
        # TODO: set proper timelines
        unit_id=Timeline[UnitId](),
        unit_level=Timeline[UnitLevel](),
        name=sd_unit_timeline.name.diff(mo_unit_timeline.name),
    )
    logger.debug("UnitTimeline diff", diff=diff)

    await update_ou_name(gql_client, org_unit, diff.name)
    await terminate_ou(gql_client, org_unit, diff.active)
